#+title: Readme
#+latex_class: VWA
#+latex_header: \class{7D}
#+options: toc:nil'
* Introduction
** Who is this class for?
Ideally it is for students of the "Sir Karl Popper Schule" or "Wiedner Gymnasium" who would like to write their VWA or VWS in LaTeX or some markup-language which they then compile to LaTeX, e.g. org-mode. But it is also meant as a starting point for students of other schools, who would like to write their own classes for their VWAs, but admittedly there would probably be better options like [[https://github.com/novoid/LaTeX-KOMA-VWA]]. If you need more examples, simply google keywords like "VWA Latex".

** Why would I choose this over Microsoft Word, LibreOffice, OpenOffice & CO?
I could write a whole rant about why Word is cooperate and proprietary shit and why it can get messy writing in an WYSIWYG-environment, but there are people who know this stuff much better than I do and can get their point across much better, so I will just mention some standard key-points regarding this debate:
- it has the best math-support out there
- it is completly free, or how Richard Stallman would put it: it is "libre" and not "gratis"
- it is WYMIWYG, this can be a pro or con point depending on your personal preferences
- you don't have to worry much about styling and pagebreaks while editing
** What editor do I have to use?
Theoretically you could write this in every editor, even notepad and vi, but I would recommend something like Texmaker, Overleaf or VSCode, preferably VSCodium, or, if you are a real try-hard or Org-mode-lover, Emacs. It really boils down to the question: "Which editor do I like best?".


* Installation
** Download and Placement
To use this class you have to clone this git repo into your latex install with this command:
#+begin_src bash
git clone https://github.com/JulianBarat/VWA-Latex-SKP.git
#+end_src
To figure out where exactly your latex install is, run this command in your terminal:
#+begin_src bash
kpsepath -n latex tex
#+end_src

For Apple-Users this will probably output many different directories, I would suggest this path, because you don't have to fiddle around much with writing-rights:
#+begin_src bash
/Users/<your_name>/Library/texlive/2022/texmf-var/tex/latex/VWA.cls
#+end_src

Note:

If you are using Overleaf you don't have to do all this; you only need to upload the VWA.cls and the img folder to your project and specify everything in the preamble.
* Custom commands
** Definitions
#+begin_src org
\newtheorem{mydef}{Definition}
\newtheorem{bsp}{Beispiel}
\newtheorem{theorem}{Satz}
#+end_src
I don't actually know what these do; I only added them for the sake of completeness.
** Commands
*** Supervisor
This variable is to be specified at the beginning of your document, in the preamble. With it you can define who your supervisor is.
It has to be done in the form of:
#+begin_src org
\supervisor{name of supervisor}
#+end_src
*** Schoolyear
This command is needed to display the correct school-year of your VWA. You do not have to specify it by hand, you just have to specify the date, which is automatically done when you use org-latex-export.
If you want to, you can also call it in the middle of your document, but it has to be done in the form of: 
#+begin_src org
\schoolyear{}
#+end_src
*** Class
This command lets you specify your class.
It belongs into the header.
#+begin_src org
\class{student's class}
#+end_src
* Usage
Some things to keep in mind while writing the VWA/S
- specify the author in the preamble
- specify your supervisor in the preamble
- specify your class in the preamble
- specify the date in the preamble
- use unnumbered sections for your abstract
- put the tableofcontents after the abstract

An example pseudocode would look like this:
#+begin_src latex
\documentclass{VWA}
\title{eine faszinierende Arbeit zu der Fortpflanzung der Stiglize}
\date{\today}
\author{Max Mustermann}
\supervisor{Herr Prof. Gruber}
\class{8m}

\begin{document}
\maketitle
\section*{Abstract}
text…

\tableofcontents

… rest of your document

\end{document}

#+end_src

* Emacs org-mode

** Adding to org-mode latex-exports
In case you want to use this class when using org-mode you have to tell that your config.el or config.org, depending on whether you have an literate config or not, and your org-preamble.

Put this into your config.el/org:
#+begin_src elisp
(with-eval-after-load 'ox-latex
   (add-to-list 'org-latex-classes
                '("VWA"
                  "\\documentclass{VWA}"
                  ("\\section{%s}" . "\\section*{%s}")
                  ("\\subsection{%s}" . "\\subsection*{%s}")
                  ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))))
#+end_src

and this at the very beginning of your .org file:
#+begin_src org
#+latex_class: VWA
#+end_src
do not forget to restart Emacs after you have modified your config files.
** Usage
When really writing your VWA you have to modify some things.

To make the abstract unnumbered you have to add this under the header:
#+begin_src org
,* abstract-header
:PROPERTIES:
:UNNUMBERED: t
:END:
#+end_src

Furthermore, if you want to follow the guidelines of our school, you have to deactivate the table-of-contents in the beginning and manually put it after your abstract.

This would be done something like this:
#+begin_src org
,#+title: some title
,#+options: toc:nil

the rest of your header...

your abstract...

\tableofcontents

rest of your document
#+end_src
* Common Issues
** Date
If the date is wrongly displayed (e.g. "24 by + 1 24/25"), try deleting "by + 1" in line 50 of VWA.cls
